### ISSUE TITLE
Deactivate Log entry on update

### ISSUE THREAD

**Issue by froststrm** [Apollon77/ioBroker.nut#1]
It would be nice to offer a checkbox in the configuration to enable or disable the log entries on update ('Start NUT update' & 'All Nut values set')!
_Reason_: When setting the update interval very short (30-60 sec) you'll get more than thousand log entries per day which is not needed in my opinion.

**Comment by Apollon77** [comment]
When you set the loglevel to warn then this logging is gone. Is this an option for you?

**Comment by froststrm** [comment]
If you mean the log level in the ioBroker admin tab, it is not a real option, because the adapter still writes into the logfile, but it is only not shown in the log view. My solution for now is, that I put a comment in the concerning lines of 'nut.js'.

**Comment by Apollon77** [comment]
No I mean the instance loglevel.

Enable expert mode (one of the buttons upper left) in instance view. Then you can set the loglevel per instance. And then logs are only written at all for what you selected there.

**Comment by froststrm** [comment]
That's a cool option, didn't know anything about this! Thanks!
