### ISSUE TITLE
Datenabfrageintervall 

### ISSUE THREAD

**Issue by XSDiVer** [Apollon77/ioBroker.nut#108]
Hallo, ich habe mein USV über ioBroker laufen,
und habe keine clients intalliert auf anderen Rechnern.

Ich fahre die Rechner per ssh herunter, je nach Akkus stand der USV.

**Was richtig gut wäre, wenn man das Pollingintervall per Datenpunkt steuern könnte,
sodass wenn das USV auf Batteriebetrieb umschaltet, man es in geringeren Abständen abfragen kann.**

Ich hoffe Ihr haltet das auch für eine gute Idee...

**Comment by Apollon77** [comment]
Effektiv fragt der Adapter den "nut" server ab und nicht due USV direkt. Ich denke nicht das Nut jedes mal beim Gerät fragt und wenn ist das seriell und braucht eher wenig eigenen strom. Ich denke nicht das das sinn macht
