### ISSUE TITLE
Driver needs to be activated with console after reboot

### ISSUE THREAD

**Issue by Roellen** [Apollon77/ioBroker.nut#114]
Hi. 
Always, after restarting iobroker on proxmox I get this error message and there is no connection to the UPS:

`Err while getting NUT values: DRIVER-NOT-CONNECTED`

After starting the driver manually with `sudo upsdrvctl start` it works fine again. 

Is this a bug from the adapter? I thought the driver would be started automatically?

Thanks!

**Comment by Apollon77** [comment]
No, this is a topic of nut. There should also be a sysetemd target for nut. Just activate it and nut should start automatically.

Check `systemctl status nut-server`
