### ISSUE TITLE
No connection on Pi bookworm

### ISSUE THREAD

**Issue by Rushmed** [Apollon77/ioBroker.nut#160]
Hi Mister.

I recently updated to bookworm.
Everything was working fine on bullseye.

No connection to nut.
`<html>
<body>

nut.0 | 2023-06-24 04:07:15.304 | error | USV not available - Delay initialization
-- | -- | -- | --
nut.0 | 2023-06-24 04:07:15.300 | error | Error happened: Error: connect ECONNREFUSED 127.0.0.1:3493
nut.0 | 2023-06-24 04:06:45.295 | error | USV not available - Delay initialization
nut.0 | 2023-06-24 04:06:45.292 | error | Error happened: Error: connect ECONNREFUSED 127.0.0.1:3493
nut.0 | 2023-06-24 04:06:15.287 | error | USV not available - Delay initialization
nut.0 | 2023-06-24 04:06:15.284 | error | Error happened: Error: connect ECONNREFUSED 127.0.0.1:3493

</body>
</html>`

Pls help!

**Comment by Apollon77** [comment]
Hm ... no idea ... is nut running on that machine? Please check nut config ... ECONNREFUSED means that connection was refused on that port on localhost. I do not have bookworm atm, so I can not tell you whats maybe changed, but check nut first ... There should be logs and such ... verify that it is running on that port first and that also local access on that port is allowed network wise.

**Comment by Rushmed** [comment]
Hi mister. Solved it.
Seems that while bookworm update process the MODE setting in /etc/nut/nut.conf was set to none.
I set it again to MODE=netserver and everything is fine.

Thanks.
