### ISSUE TITLE
Log info

### ISSUE THREAD

**Issue by Brainbug01** [Apollon77/ioBroker.nut#32]
Hallo,

ist es möglich die Infomeldung:

nut.0 | 2019-12-01 13:16:25.002 | info | (4210) All Nut values set
nut.0 | 2019-12-01 13:16:24.890 | info | (4210) Start NUT update

die mit dem Aktualisierungsintervall von 300s immer im Log steht auf einem andere Log-Stufe zu verschieben? Ich finde das diese Meldung nicht alle 300s im Log stehen muss.

**Comment by Apollon77** [comment]
Dann ändere doch einfach das loglevel der Instanz auf warn. 

Dazu: Instanzen ... expertenmodus ... Spalte loglevel.
