### ISSUE TITLE
Adapter aktuell nutzbar mit Synology Diskstation und JS-Controller 3.x?

### ISSUE THREAD

**Issue by capitaenz** [Apollon77/ioBroker.nut#48]
Moin zusammen,

kann ich diesen Adapter gefahrlos in einem aktuellen ioBroker System einsetzen mit JS-Controller 3.x?
Die Daten der USV kommen von einer Synology Diskstation.

Danke für die Antwort
Leif

**Comment by Apollon77** [comment]
ja klar ... warum nicht?

**Comment by capitaenz** [comment]
Ich frage, weil dieser im ioBroker direkt nicht auftaucht und von Github installiert werden muss.
Danke, werde morgen testen. 👍

**Comment by Apollon77** [comment]
Ääähm der nut adapter ist natürlich im Repository in Version 1.1.3 im Stable und Latest schon ewig

**Comment by capitaenz** [comment]
Hm, ich habe gesucht... unter "nut", "iobroker", "usv", "ups", aber konnte den Adapter über die Suche des ioBroker nicht finden!
Habe jetzt direkt über Github installiert.
Läuft! Danke!
