### ISSUE TITLE
connect EHOSTUNREACH

### ISSUE THREAD

**Issue by Anzic23** [Apollon77/ioBroker.nut#51]
The adapter has stopped working. I get the following error in the log:
	(29087) Error happend: Error: connect EHOSTUNREACH 192.168.1.38:3493
my version of DSM 6.2-23739
Internet searches have led to this [page](https://www.reddit.com/r/synology/comments/bbqtdv/warning_network_ups_tools_nut_clients_fail_after/ekmseub/), but failed to verify everything described there (connection via telnet).

---

**System data:**

Platform: linux
Distribution: Debian GNU/Linux
Architecture: x64
Model: Intel(R) Celeron(R) CPU G1610T @ 2.30GHz
RAM: 9.73 GB
Node.js: v12.17.0
NPM: 6.14.5
Model: unknown
RAM: 987.98 MB
Node.js: v12.17.0
NPM: 6.14.4
Model: ARMv7 Processor rev 4 (v7l)
RAM: 975.6 MB
Node.js: v12.17.0
NPM: 6.14.5
JS-Controller (1): 3.1.4
Admin: 4.1.1
Network UPS Adapter: 1.1.3

> *created by ioBroker.info*

**Comment by Apollon77** [comment]
EHOSTUNREACH 192.168.1.38 means that the IP is not reachable... Please check your network and maybe try to use a nut client to connect to this ... see Adapter Readme for details
