### ISSUE TITLE
No or wrong info after click "?" for Adapter Info

### ISSUE THREAD

**Issue by wendy2702** [Apollon77/ioBroker.nut#6]
Hi Ingo,

allready discussed at https://forum.iobroker.net/viewtopic.php?f=36&t=3253&start=60#p138011

Maybe same problem as for Smartmeter Adapter : https://github.com/Apollon77/ioBroker.smartmeter/issues/11 !?

Br

**Comment by Apollon77** [comment]
please update to latest version and retry

**Comment by wendy2702** [comment]
Hi,

just installed Version 1.1.3 from git and the problem is solved.

Thanks
