### ISSUE TITLE
Bitte in Description aufnehmen...

### ISSUE THREAD

**Issue by olderbag** [Apollon77/ioBroker.nut#62]
...dass bei QNAP NAS der Name der USV "qnapnas" lauten muss.

Danke

**Comment by olderbag** [comment]
Datei editiert - erledigt.

**Comment by Apollon77** [comment]
Was hast du wo editiert?

**Comment by olderbag** [comment]
Ähm... da:
[image: Zwischenablage01.jpg]
Und dann "propose changes".

Kann man das nicht so machen? Sorry, bin nicht so firm in diesen Dingen...

Beste Grüße
Manfred


Am Fr., 15. Jan. 2021 um 18:18 Uhr schrieb Ingo Fischer <
notifications@github.com>:

**Comment by Apollon77** [comment]
Doch, und dann noch "pull request senden "oder so ... ist nämlich nix angekommen :-)

**Comment by olderbag** [comment]
Okay, fügst du die Zeile jetzt ein oder soll ich noch mal? :)

Ingo Fischer <notifications@github.com> schrieb am Fr., 15. Jan. 2021,
19:58:

**Comment by Apollon77** [comment]
versuchs gern nochmal :-)

**Comment by olderbag** [comment]
morgen😴

Gruß
Manfred

Ingo Fischer <notifications@github.com> schrieb am Fr., 15. Jan. 2021,
21:52:
