### ISSUE TITLE
UPS Network Management Card 2

### ISSUE THREAD

**Issue by smooty1970** [Apollon77/ioBroker.nut#64]
Hallo.

Ich hätte versucht meine APC UPS mittels eingebauter UPS Network Management Card 2 über den Adapter auszulesen.
Ist das überhaupt möglich? Gibt es hier hinsichtlich Name, Port und Zugangsdaten Besonderheiten?

Danke

**Comment by Apollon77** [comment]
Ehrlich? Keinen blassen Schimmer, da ich sowas nicht habe. Wenn ich aber die Specs überfliege macht das ding nur nen Webserver auf ... das dürfte kein NUT protokoll sein ... also am ende ... ggf auf klassischem weg per "datenport" an einen rechner per USB anschliessen?

**Comment by gidhap** [comment]
@smooty1970 
Falls das so aussieht wie beio mir:
Sie Network Management Card in meiner APC kann SNMP
Ich habe einfach den [SNMP Adapter](https://github.com/iobroker-community-adapters/ioBroker.snmp) installiert.
Bei der Konfiguration brauchst DFu nur die IP Adresse und die [Object Identifiers (OIDs](https://www.opsview.com/resources/monitoring/blog/apc-ups-monitoring-useful-oids)). Ich kopiere die hier mal rein, denn bei verlinkten URLs weiss man nie wie lange sie funktionieren.

`For APC UPS monitoring, here are some of the OIDs (Object Identifiers) you'll want to use. These OIDs definitely work with the APC AP9617 management card which plugs in the back of APC devices.

General UPS Monitoring Info
UPS Type             .1.3.6.1.4.1.318.1.1.1.1.1.1.0

String containing UPS model, eg: Smart-UPS 1000

Battery Information
Battery capacity             .1.3.6.1.4.1.318.1.1.1.2.2.1.0

Battery capacity as % of total

Battery temperature         .1.3.6.1.4.1.318.1.1.1.2.2.2.0

Battery temperature in Celcius of Farenheit - depending on how UPS is configured

Battery runtime remain         .1.3.6.1.4.1.318.1.1.1.2.2.3.0

Total battery runtime available based on current load.

Battery replace             .1.3.6.1.4.1.318.1.1.1.2.2.4.0

If result = 2 then battery needs replacing (1 = ok)

UPS Input
Input voltage             .1.3.6.1.4.1.318.1.1.1.3.2.1.0

Input voltage, to the UPS device

Input frequency             .1.3.6.1.4.1.318.1.1.1.3.2.4.0

Input frequency in Hz

Reason for last transfer         .1.3.6.1.4.1.318.1.1.1.3.2.5.0

String containing reason for last transfer to battery power

1  No events
2  High line voltage
3  Brownout
4  Loss of mains power
5  Small temporary power drop
6  Large temporary power drop
7  Small spike
8  Large spike
9  UPS self test
10  Excessive input voltage fluctuation

UPS Output
Output voltage             .1.3.6.1.4.1.318.1.1.1.4.2.1.0

Output voltage from the UPS

Output frequency             .1.3.6.1.4.1.318.1.1.1.4.2.2.0

Output frequency in Hz

Output load             .1.3.6.1.4.1.318.1.1.1.4.2.3.0

Output load expressed as % of capacity

Output current             .1.3.6.1.4.1.318.1.1.1.4.2.4.0

Output current in Amps

Diagnostics
Comms             .1.3.6.1.4.1.318.1.1.1.8.1.0

Whether SNMP agent is communicating with UPS device 1 = yes, 2 = no

Last Self Test result         .1.3.6.1.4.1.318.1.1.1.7.2.3.0

Result of last self test as text string. eg: pass or fail.

Last Self Test date         .1.3.6.1.4.1.318.1.1.1.7.2.4.0

Date of last self test`

![image](https://user-images.githubusercontent.com/28500973/107957788-692e6c80-6fa1-11eb-847c-d2ce94be7949.png)

![image](https://user-images.githubusercontent.com/28500973/107958011-b3175280-6fa1-11eb-9ae3-fbf233b0cf56.png)

**Comment by Apollon77** [comment]
Ok, when SNMP then  I can close here, or?

**Comment by gidhap** [comment]
Good for me :)
