### ISSUE TITLE
Probleme mit Nut unter windows 10

### ISSUE THREAD

**Issue by Matten-Matten** [Apollon77/ioBroker.nut#68]
Moin,

ich hab den Nut dienst unter win 10 laufen aber der adapter schmeißt nach dem start folgende meldung aus und
folglich auch keine Meldung.

`

nut.0 | 2021-03-21 12:40:41.270 | error | (1244) Err while getting NUT values: DATA-STALE
-- | -- | -- | --
nut.0 | 2021-03-21 12:40:41.258 | error | (1244) Err while getting all commands: DATA-STALE
nut.0 | 2021-03-21 12:40:41.171 | info | (1244) starting. Version 1.4.3 in C:/ioBroker neu/SmartHome/node_modules/iobroker.nut, node: v10.17.0, js-controller: 3.1.6
host.ioBroker(SmartHome) | 2021-03-21 12:40:36.765 | info | instance system.adapter.nut.0 started with pid 1244

`

**Comment by Apollon77** [comment]
Bitte mal manuell mit den test Skripten versuchen - siehe https://github.com/Apollon77/ioBroker.nut#troubleshooting
... Was geben die mormalen nut CLI Tools denn unter wimdows aus?

Ansonsten wurde sowas schon mal unter https://forum.iobroker.net/post/284225 diskutiert.

Ich denke eher es liegt an EInstellungen wie die USV abzufragen ist. DATA-STALE heisst an sich das Du alte Daten bekommst anstelle aktuelle weil er keine aktuellen Daten lesen konnte.

**Comment by Matten-Matten** [comment]
Moin, sorry aber mangels Zeit und komponenten kann ich hier nichts an Infos weiter zu steuern.
Nut läuft erfolgreich auf meiner Raspberrymatic. Ich hatte gehofft die USV auch "easy" mit ioBroker verbinden
zu können. 

Danke trotzdem für die Hilfe!
mache ich hier zu.
