### ISSUE TITLE
Daten werden nach Update des NAS (Synology DS218J) nicht mehr aktualisiert 

### ISSUE THREAD

**Issue by Castlehub** [Apollon77/ioBroker.nut#73]
Hallo,
ich habe nach dem updaten des NAS (aktuell DSM 6.2.4-25556) festgestellt, d. die Daten im Iobroker nicht mehr aktualisiert werden und die Verbindung mit folgende Fehlermeldung fehl schlägt:

![fehler01](https://user-images.githubusercontent.com/70769414/115963857-a1ae7180-a521-11eb-8289-4556976888ce.JPG)

Im NAS wurden keine Veränderungen vorgenommen.

![image](https://user-images.githubusercontent.com/70769414/115963889-d9b5b480-a521-11eb-90fa-86ba6ad74aa2.png)

Ist das Problem bekannt oder kann man es eventuell durch eine andere Einstellung beheben?

**Comment by Apollon77** [comment]
ECONNREFUSED heisst das die verbindung nicht erlaubt wird. Ist die IP des Geräts freigegeben?  (Button "zugelassene Disksattion Geräte")

**Comment by Castlehub** [comment]
> ECONNREFUSED heisst das die verbindung nicht vergessen wird. Ist das IP des Betroffenen Gebengebens? (Schaltfläche "Verfüge Disksattion Geräte")

Die IP vom IoBroker ist im NAS hinterlegt und wurde nicht geändert. 

![image](https://user-images.githubusercontent.com/70769414/115971041-8b66dc80-a546-11eb-98b0-432c9740f865.png)

Und laut Zeitstempel war die letzte Aktualisierung zum Zeitpunkt des NAS-Updates:

![bildschrim-1](https://user-images.githubusercontent.com/70769414/115971352-43e15000-a548-11eb-844f-140f79728301.jpg)

**Comment by Apollon77** [comment]
Ich kann leider nicht mehr sagen als das obige. ECONNREFUSED heisst das der Hst die Netzwerkverbindung ablehnt. Vllt NAS nochmal neu starten?

**Comment by pdbjjens** [comment]
@Castlehub 
This is a known issue of Synology DSM 6.2.4-25556, which can be circumvented by a [Temporary Fix](https://community.synology.com/enu/forum/1/post/141910?page=1&sort=oldest)
`In dsm ups section, desactivate server network ups, save, reactivate it and write the ip allowed  Save again

and on nut clients deactivate and reactivate the service`

**Comment by capitaenz** [comment]
Danke @pdbjjens, der Tipp hat geholfen.
