### ISSUE TITLE
JS-Controller 3.3 - LOG-Eintrag State value to set for "nut.0.battery.charge" has wrong type "string"

### ISSUE THREAD

**Issue by kueppert** [Apollon77/ioBroker.nut#74]
nut.0 | 2021-04-30 10:08:23.595 | warn | (19229) State value to set for "nut.0.battery.charge" has wrong type "string" but has to be "number"

**Comment by SaimenSays** [comment]
Ich denke das wird schnell gefixt, @Apollon77 hat dieses Thema selbst ins Rollen gebracht: https://forum.iobroker.net/post/622288
