### ISSUE TITLE
Some values are not updated, only at restart

### ISSUE THREAD

**Issue by jogicom** [Apollon77/ioBroker.nut#9]
Values such as runtime, charge, load etc. are not updated on change, the values are only updated when the nut adapter is restarted. If the values change during operation, they are not updated. The values are read in once by the UPS (Synology) when the nut adapter is started. All other operating states are displayed correctly, even if changes are made.

**Comment by Apollon77** [comment]
Please enable debug mode for the instance and provide that log. It is working fine for me with APC USVs. The values are only updated if the value changes! All values should be read on defined Intervall.

**Comment by Apollon77** [comment]
Deutsch auch ok ;-)

Am besten checke mal Logs von damals. An sich ist die nur Verbindung nicht persistent und wird bei jedem Lauf neu aufgebaut. Es sollte also egal sein wenn der Server weg ist, dann sollte ein Fehler stehen.

**Comment by jogicom** [comment]
Mist, LOGs sind weg, da zu lange her.... Ich werde am besten mit aktiviertem DEBUG das am Wochenende mal nachstellen, dass der SynoDienst für die USV hing, kann ja nicht sein, da ich nur den NUT-Adapter neu gestartet habe und nun sind alle Werte da und werden auch aktualisiert... ich melde mich wieder sobald ich das getestet habe.

**Comment by Apollon77** [comment]
Auch die auf Platte weg? /opt/iobroker/log/...

**Comment by jogicom** [comment]
LOGs sind leider nur bis 17.11 vorhanden und der Ausfall war davor.... vermutlich bin ich einen Tag zu spät dran :-)  Wie immer!

**Comment by jogicom** [comment]
Ich glaube das Issue kann man schliessen. Mein Versuch heute ging gewaltig in die Hose, da der Raspi hart abgeschaltet wurde, habe da wohl bei einem Javascript Update was übersehen:
2018-11-24 12:02:07.546  - [33mwarn[39m: javascript.0 script.js.Ueberwachung.UsvShutdown: !!!!====>>>>Homevision Shutdown Service initiated, USV Battery LOW<<<<====!!!!
2018-11-24 12:02:37.549  - [31merror[39m: javascript.0 exec is not available. Please enable "Enable Exec" option in instance settings
Das Programm, das den Raspi und IObroker geordnet runter fahren soll, wurde nicht ausgeführt.

Nachdem ich den Raspi mit IObroker wieder repariert habe, werden alle Werte richtig aktualisiert, der einzige Wert der bei 0 hängen bleibt ist der load-Wert (momentane Last) . Könnte aber auch der USV dienst der Synology sein, der das nicht aktualisiert. Werde mal weiter forschen und das ganze länger beobachten. Evt. wurde schon früher der RASPI hart abgeschaltet und ich hatte deswegen die Problemchen....sorry!

**Comment by Apollon77** [comment]
Alles klar. Falls du mehr Infos findest wieder auf machen ;-)

**Comment by capitaenz** [comment]
Hm, ich habe gesucht... unter "nut", "iobroker", "usv", "ups", aber konnte den Adapter über die Suche des ioBroker nicht finden!
Habe jetzt direkt über Github installiert.
Läuft! Danke!
